name = "Bingchill"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1ef7026b9bd7d6cab16d1c2f917b353cf98cccaf5d959005c986884a266ce96"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"
