name = "Bingchill"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c721da1fc97eb35f9b4490b15954ac86c855ca4fb1aac6edfdd94fcebdce796"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
