name = "Bingchill"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ad7e768ba825488c15d466df08ecea1e5511cb5c2dec23f3804b0e4439040dd"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
