name = "Test"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca3438d8e7b9b1582d3367461536d08abfcaa5fc15526a73ca6cadbf300f11a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2-beta.2"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1", "1.19"]
datapack-folder = "/resources/packs/"
