name = "Test"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9797d73c6912ee9866303455a0c91cf9f782f92b630af0d6e8299cf890bfd27c"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1", "1.19"]
