name = "Forge"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "368beea2ef1f7b3d1eab51c96dc6ea6740260e607baa0b6c1b57dac1825c3f77"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
