name = "Forge"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed5a93cafd821b29ec87acd62e70d985c5332cf4d4269bc56137ab9762f4d2f"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
