name = "Forge"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c4fe4b4b639b5860849d2f249a3484a490401b81115152ae57ff7fe4fb20f4c"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
