name = "Forge"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58b2334d4228573d5abaa171eb5840301bf4819ab16f52209c314e34569d817"

[versions]
forge = "43.2.12"
minecraft = "1.19.2"
