name = "Forge"
author = "Monke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "328ff09cfbf82491111aac95fd63680bd2ab95045c098de3bc73664bc999fbbd"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
